title: "Rossetta"
email: dpoloa@uninorte.edu.co 
timezone: UTC
baseurl: ''
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'beta'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
authors:
  sal:
    name: David Alejandro Sanchez Polo
    display_name: lasagna0
    avatar: 'assets/images/sal.png'
    email: dpoloa@uninorte.edu.co
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Economista apasionado por la programacion. Analista de datos."


# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
